name: Main

on: push

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: yarn --frozen-lockfile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Test
        run: yarn test
